name: React CI + SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:    
    runs-on: ubuntu-latest

    steps:

      # 1️⃣ Checkout Code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # 3️⃣ Install Dependencies
      - name: Install Dependencies
        run: npm install

      # 4️⃣ Run Tests
      - name: Run Tests
        run: npm test -- --watchAll=false
        continue-on-error: true

      # 5️⃣ Build React App
      - name: Build Project
        run: npm run build

      # 6️⃣ SonarQube Scan (For React / JS Project)
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          args: >
            -Dsonar.projectKey=hotstar-react-app
            -Dsonar.sources=src
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST }}
